name: Feature Request
description: Suggest a new skill or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe your idea below.

  - type: dropdown
    id: type
    attributes:
      label: Request Type
      description: What kind of request is this?
      options:
        - New skill
        - Skill improvement
        - New agent
        - Documentation improvement
        - Tooling improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your suggestion
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: How would this help you or others?
      placeholder: This would help when...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Any examples or references?
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute?
      options:
        - label: I'm willing to help implement this
